### ISSUE TITLE
when i use web-kit-filter where can i found the filtered image 

### ISSUE THREAD

**Issue by pradeepaanumalla** [peterpeterparker/web-photo-filter#1]
I am using ionic3 and i followed the process that u described,but where can i found the filtered image.As i want to display the filtered image
My ts will look like this
import { Component } from '@angular/core';
import { IonicPage, NavController, NavParams } from 'ionic-angular';
import { Camera, CameraOptions } from '@ionic-native/camera';
import { ImagePicker } from '@ionic-native/image-picker';
import { Crop } from '@ionic-native/crop';
import 'web-photo-filter';

/**
 * Generated class for the EditPage page.
 *
 * See https://ionicframework.com/docs/components/#navigation for more info on
 * Ionic pages and navigation.
 */

@IonicPage()
@Component({
  selector: 'page-edit',
  templateUrl: 'edit.html',
})
export class EditPage {
  newPhoto:any;
  photonew:any;
  filter:string='null';
  constructor(public navCtrl: NavController, public navParams: NavParams,
  		      private camera:Camera,
              private imagePicker:ImagePicker,
              private crop: Crop) {
  }

  ionViewDidLoad() {
    console.log('ionViewDidLoad EditPage');
  }

  pickPhoto(){
    const options: CameraOptions = {
	    quality: 70,
	    destinationType: this.camera.DestinationType.DATA_URL,
	    encodingType: this.camera.EncodingType.JPEG,
	    mediaType: this.camera.MediaType.PICTURE,
	    saveToPhotoAlbum:true,
	    allowEdit:true
  	}
    this.imagePicker.getPictures(options).then((results) => {
      for (var i = 0; i < results.length; i++) {
          console.log('Image URI: ' + results[i]);
      }
      this.newPhoto=results[0];
    }, (err) => { });
  }

  cropPhoto(pic){
  		this.crop.crop(pic, {quality: 75})
		  .then(
		    newImage => {
		    	console.log('new image path is: ' + newImage);
		    	this.photonew=newImage;
		    },
		    error => console.error('Error cropping image', error)
		 );
  }
  effectOne(){
    console.log(this.newPhoto);
    console.log("one");
    this.filter="sepia";     
  }effectTwo(){
    console.log(this.newPhoto);
    console.log("two");
    this.filter="blue_monotone";     
  }effectThree(){
    console.log(this.newPhoto);
    console.log("three");
    this.filter="violen_tomato";     
  }
}

My html file is

![capture](https://user-images.githubusercontent.com/37704663/38781759-dc484860-4107-11e8-9a53-bbb8522eab62.PNG)

If u respond as soon as possible it will be helpful,thanks

**Comment by peterpeterparker** [comment]
could you plz edit your issue, format your code (four spaces begin of each lines), add the missing html code and the images you uploaded aren't displayed

**Comment by pradeepaanumalla** [comment]
yeah, added it,please check

**Comment by peterpeterparker** [comment]
you still didn't format your code...

anyway

    <web-photo-filter src="{{newPhoto}}" filter="{{filter}}"></web-photo-filter>

would be correct. you could also encapsulate it in a div till `newPhoto` would be defined, for example

    <div *ngIf="newPhoto != null">
          <web-photo-filter src="{{newPhoto}}" filter="{{filter}}"></web-photo-filter>
    </div>

check in your Google Chrome debugger for example that the component is correctly rendered in the DOM

also correct the default value of your `filter`, not `'null'` but `null`

     filter: string = null;

I close this issue since it isn't an issue but a support question. Feel free to open a question and Stackoverflow or the Ionic Forum and to link it here

**Comment by pradeepaanumalla** [comment]
Where can I find this filtered image,like for this new photo Iam applying
the filter.so,it will store somewhere else or what ?

**Comment by peterpeterparker** [comment]
have a look to the DOM and you will understand.

you provide an image/photo to the component, the component create a canvas where the style will be applied

**Comment by pradeepaanumalla** [comment]
If I given the filter value as null and as well as in some functions I
defined 'sepia' but that sepia filter is also not working

**Comment by pradeepaanumalla** [comment]
Ok, I will try
