### ISSUE TITLE
Use angular-cropper with filtered images 

### ISSUE THREAD

**Issue by Shtibel** [peterpeterparker/web-photo-filter#12]
Hi there,
I need to implement [angular-cropper](https://github.com/matheusdavidson/angular-cropperjs) with the filtered image result.
So to be able to crop before the image was filtered and after the image was filtered.
How can I do it?

I watched [this video](https://www.youtube.com/watch?v=SNt-sqP_2D4).
And I see there that there is a crop option
That is what I want to accomplish.

**Comment by peterpeterparker** [comment]
This question is kind of out of the scope of the component. You get the result with `filterLoad` and then you should init your cropper with it

These are the source of the video you are referencing. I don't use angular-cropper but cropper.js but you'll probably be able to reconstruct something from there:

https://github.com/fluster/fluster-app/tree/5688451cc3752dcde0cde9bd142ef73193a41c5c/src/app/modals/core/photo-picker

**Comment by Shtibel** [comment]
Hi @peterpeterparker 
I managed to combine the cropper with the filter !
Thank you!

![20190612_221953](https://user-images.githubusercontent.com/24429607/59379866-6c02a400-8d60-11e9-8d6d-8e696b80293e.gif)

**Comment by peterpeterparker** [comment]
@Shtibel yeahhhh well done 👍

**Comment by Shtibel** [comment]
Loving your component 
Well done !
