### ISSUE TITLE
Large weight image not working

### ISSUE THREAD

**Issue by Shtibel** [peterpeterparker/web-photo-filter#13]
Hi there,
I am trying to do a filter on a large weight image and the filters are not showing and not working.

I take an image from the local device library that weight 8 MB and none of the filters show and work.

![20190613_005729](https://user-images.githubusercontent.com/24429607/59389200-6b750800-8d76-11e9-8d11-aa611a46cd87.gif)

**Comment by peterpeterparker** [comment]
I faced the same problem in my app. Not related to the component but rather to the device or browser and WebGL canvas.

Anyway you could solve this by using a smaller image size for your effects picker.

You load an image, keep the large one to apply the effect and create a reduced one which you use only for the picker.

**Comment by Shtibel** [comment]
Hy @peterpeterparker ,
I solved this problem by resizing the image before opening the filtering page.
Working with the: [cordova-plugin-image-resizer](https://github.com/JoschkaSchulz/cordova-plugin-image-resizer) plugin.

Here is he code:
```js
let options: ImageResizerOptions = {
  uri: image.fileUrl,
  quality: 90,
  width: 1280,
  height: 1280,
  base64: true
};
this.imageResizer.resize(options).then((res) => {
  image.fileUrl = res;
  let myModal = this.modalCtrl.create('EditImagePage',{
    image: image
  });
  myModal.present();
});
```

**Comment by peterpeterparker** [comment]
@Shtibel coolio, well done 👍
