### ISSUE TITLE
Using An Image From Https

### ISSUE THREAD

**Issue by ewwwgiddings** [peterpeterparker/web-photo-filter#14]
Is there any way to use an image from an https path if we are in control of where that image is stored? For example, if we have it stored on Azure Storage or on our own server?

I think why it is not allowed is because of CORS. If that is true, the error I get when I try to do this with web-photo-filter is usually solved by setting crossorigin on the img tag.

Is there a way to set the crossorigin attribute on the image element to possibly allow for using images from an https origin?

Has anyone found out any way to use an https image src?

**Comment by ewwwgiddings** [comment]
The only way I have found so far is to use Fetch to get the image from the URL, then convert that toDataURL using FileReader, and then use that DataURL as the src of the component.

I would like to be able to just set the crossorigin attribute on the component though to get images from URLs I control instead of having to use Fetch with credentials for CORs set (https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch) and then FileReader(https://developer.mozilla.org/en-US/docs/Web/API/FileReader).

Any idea how we could make this happen on this so that at least https origins are allowed for people who control the file's origin?

**Comment by peterpeterparker** [comment]
There is currently no `crossorigin` attribute set to the image but if that would solve your requirements, of course I would not be against such an option. If you would like to provide a PR which add a new property and set the attribute to the img, I'll be happy to merge it

**Comment by peterpeterparker** [comment]
The `crossorigin=anonymous` attribute has been added in PR [#22](https://github.com/peterpeterparker/web-photo-filter/pull/22) and will be release in upcoming v3.
