### ISSUE TITLE
I just can't get this library work :(

### ISSUE THREAD

**Issue by varunj166** [peterpeterparker/web-photo-filter#25]
Hey man. First, I really appreciate you taking the time to make this library. I am **very** interested in having image photo filter functionality of the type you describe and demonstrate on the home page for this library.

The problem is, I just can't get it to work! I've tried everything I can think of.

So I've created a very small test project that I'm hoping you could look at, and let me know what I'm doing wrong:
https://github.com/varunj166/web-photo-filter-testing

All it contains is the react `WebPhotoFilter` component (which doesn't seem to work), as well as the actual `web-photo-filter` web component (which was a last ditch effort to get something to show up on the page).

**PLEASE** take a moment and let me know what's wrong. I'm sure it's something simple.

Thanks!

**Comment by peterpeterparker** [comment]
Can you try to modify your import as following:

```
import {defineCustomElements} from 'web-photo-filter/dist/loader';
defineCustomElements();

import {WebPhotoFilter} from 'web-photo-filter-react/dist';
```

Respectively replace your `import 'web-photo-filter';` with the above `loader`.

That's what I do in one of my React app and it works out for me.

See https://github.com/peterpeterparker/rebelscan/blob/8bb9b095491bfcc5cc538521569d8a82afbcc622/src/components/home/Home.tsx#L3 in my Rebel Scan small app.

**Comment by varunj166** [comment]
@peterpeterparker  Thanks a lot for the quick reply and proposed solution! I'll give it a shot as soon as I have a free moment.

**Comment by varunj166** [comment]
Hey @peterpeterparker, so your `defineCustomElements` fix worked for loading the component (thanks!), but I'm unable to hook into the `onFilterLoaded` event. This seems like it should be the simplest part. Am I again doing something wrong?

```javacript
function App() {
  const imgSrc =
    'https://raw.githubusercontent.com/peterpeterparker/web-photo-filter/master/assets/demo/instagram.jpg';

  const handleFilterLoaded = (event) => {
    // This doesn't fire :(
    console.log(event);
  };

  return (
    <div>
      <h1>Web Photo Filter Testing</h1>
      <WebPhotoFilter
        src={imgSrc}
        filter="sepia"
        onFilterLoaded={handleFilterLoaded}
      />
    </div>
  );
}
```

**Comment by peterpeterparker** [comment]
Can you try `onFilterLoad` ? No `ed` at the end.

**Comment by varunj166** [comment]
Hahaha oh boy... That was embarrassing. Yes, even your typings say `onFilterLoad`. It was late at night when I was working on this last week.

Thanks for all your help! I'll close this issue.

**Comment by varunj166** [comment]
Excellent responses from the library author.

**Comment by peterpeterparker** [comment]
Haha no worries, with a -ed the event would have make sense too 😉

Happy to hear it worked out!
