### ISSUE TITLE
webphotofilter.js not working in Ionic

### ISSUE THREAD

**Issue by alessandrom80** [peterpeterparker/web-photo-filter#28]
Hi I followed Simon Grimm's guide for Ionic step by step on https://devdactic.com/ionic-photo-filters-instagram/

When I start the project I get the error http: // localhost: 8100 / webphotofilter.js ERR_ABORTED 404

From what I saw in the dist of the node_module there is no js file. How can I solve? Thank you very much!

**Comment by peterpeterparker** [comment]
Looks like the component is either not installed or imported. Double check that both install and import are in place.

If still does not work, you are most welcomed to provide a sample repo.

**Comment by alessandrom80** [comment]
Thanks to the availability.

The error remains 404. I created a new project following the tutorial step by step. I just can't figure out what it's due to. Could it be the distribution that has changed in the meantime?

The test repository can be downloaded at this address:
https://github.com/alessandrom80/testwebphotofilter.git

Error: ![image](https://user-images.githubusercontent.com/70145977/128325656-583fe9d2-d170-40be-b3f1-a5145a36f619.png)

Thanks again.

**Comment by peterpeterparker** [comment]
@alessandrom80 sh*t sorry missed the notifications with your sample repo, gonna have a look now

**Comment by peterpeterparker** [comment]
Yep indeed it is what I meant in my first message, you did not load the component.

Add following in `main.ts` to load the web component:

```
import { defineCustomElements as webPhotoFilterCustomElements } from 'web-photo-filter/dist/loader';
webPhotoFilterCustomElements();
```

In addition, the `filter` cannot be an empty string. Set it to `undefined` or to a default filter.

```
selectedFilter = 'sepia';

// or

selectedFilter = undefined;

```

Doing so, all good.

Again, sorry for the delay.

<img width="1317" alt="Capture d’écran 2021-08-13 à 13 27 33" src="https://user-images.githubusercontent.com/16886711/129350744-ee9cbe49-1fdf-45ce-b4f5-4ad422553067.png">

**Comment by alessandrom80** [comment]
Don't worry about the wait, indeed thanks for the time you took.
I wish you good things.
Good day.
