### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by solitudeYu** [peterpeterparker/web-photo-filter#29]
I can't seem to use it

![image](https://user-images.githubusercontent.com/53744893/137055172-8a5992be-18d2-448e-a87f-601a12f3386f.png)

WebPhotoFilter is undefined

I saw

![image](https://user-images.githubusercontent.com/53744893/137055260-093b91d2-78e5-427b-877f-102be06bba2c.png)

Empty file

**Comment by peterpeterparker** [comment]
You most probably did not load the component correctly.

As an example, you can have a look to this project to see how it can be done: https://github.com/peterpeterparker/rebelscan
