### ISSUE TITLE
Typos on website

### ISSUE THREAD

**Issue by rtpHarry** [peterpeterparker/web-photo-filter#7]
Couldn't find a repo for the website itself, so I'm submitting it here:

![image](https://user-images.githubusercontent.com/1038062/47253526-3f6ee480-d47e-11e8-8aca-33f9e7cb6342.png)

![image](https://user-images.githubusercontent.com/1038062/47253534-4990e300-d47e-11e8-9fe8-9ac9279fb13f.png)

**Comment by peterpeterparker** [comment]
@rtpHarry thx a lot for the issue, you are right, there was a typo not just in the website but also in the component itself. it's now fixed and release in v2.2.0 😃

p.s.: there isn't any particular repo for the website because `src/index.html` is the website page itself 😉
