### ISSUE TITLE
Install on Ionic 3

### ISSUE THREAD

**Issue by Shtibel** [peterpeterparker/web-photo-filter#9]
Hi,
What is the way to install this component on an Ionic 3 project?

Thank you

**Comment by peterpeterparker** [comment]
You could try out something like described in a PR of another web component I published:

https://github.com/fluster/web-social-share/pull/6/commits/26fb97d02de98722045418a2812ae02617b96706

Let me know if it works but generally speaking I'm more focus to support recent versions

**Comment by Shtibel** [comment]
Hi @peterpeterparker,
Thank you for the quick response !
I followed [Simon Grimm tutorial](https://ionicacademy.com/ionic-image-filter-webgl/).
It is tutorial for version: 1.1.1
The problem now is that the canvas result is not showing.
I tried it with 1.1.1 and 2.1.1 
See my issue I opened about it: https://github.com/fluster/web-photo-filter/issues/10
